flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- HTTP-4000.2.22
- HUnit-1.3.0.0
- MissingH-1.3.0.1
- OneTuple-0.2.1
- StateVar-1.1.0.1
- adjunctions-4.2.2
- async-2.0.2
- base-orphans-0.4.4
- bifunctors-5.1
- comonad-4.2.7.2
- contravariant-1.3.3
- data-ordlist-0.4.7.0
- distributive-0.4.4
- exceptions-0.8.0.2
- fgl-5.5.2.3
- file-embed-0.0.9
- free-4.12.1
- hashable-1.2.3.3
- hslogger-1.2.9
- kan-extensions-4.2.3
- lens-4.12.3
- mtl-2.2.1
- multiset-0.3.0
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.0.6
- parsec-3.1.9
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.2
- random-1.1
- reflection-2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- safe-0.3.9
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- split-0.2.2
- stm-2.4.4
- tagged-0.8.2
- text-1.2.1.3
- transformers-compat-0.4.0.4
- tuple-0.3.0.2
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- void-0.7.1
resolver: ghc-7.10.3
