# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: ghc-7.10.3

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [HTTP-4000.2.22, HUnit-1.3.0.0, MissingH-1.3.0.1
  , OneTuple-0.2.1
  , async-2.0.2, data-ordlist-0.4.7.0, fgl-5.5.2.3, file-embed-0.0.9
  , lens-4.13, mtl-2.2.1, multiset-0.3.0, old-locale-1.0.0.7, parsec-3.1.9, safe-0.3.9
  , split-0.2.2, text-1.2.1.3, tuple-0.3.0.2
  , base-orphans-0.4.4, bifunctors-5.1, comonad-4.2.7.2, contravariant-1.3.3
  , distributive-0.4.4, exceptions-0.8.0.2, free-4.12.1, hashable-1.2.3.3
  , hslogger-1.2.9, kan-extensions-4.2.3, network-2.6.2.1, old-time-1.1.0.3
  , parallel-3.2.0.6, profunctors-5.1.2, random-1.1, reflection-2.1
  , regex-compat-0.95.1, semigroupoids-5.0.0.4, semigroups-0.18.0.1
  , stm-2.4.4, tagged-0.8.2, transformers-compat-0.4.0.4
  , unordered-containers-0.2.5.1, vector-0.11.0.0, void-0.7.1
  , StateVar-1.1.0.1, network-uri-2.6.0.3, prelude-extras-0.4.0.2
  , regex-base-0.93.2, regex-posix-0.95.2
  , adjunctions-4.2.2, primitive-0.6.1.0]

# Override default flag values for local packages and extra-deps
flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
